defaults:
  - base_defaults
  - _self_

wandb_exp_name: "${job.name}"
wandb_project: "sanity-checks"
wandb_save_dir: "${job.base_output_dir}/wandb"
tensorboard_dir: "${job.base_output_dir}/tensorboard"
save: "${job.base_output_dir}"
load: "${job.base_output_dir}"
config_logger_dir: ""
data_cache_path: ${oc.env:OELLM_CACHE_DIR,".cache"}
ckpt_format: torch_dist  # use default for distributed training
save_interval: 5000
eval_interval: 5000
encoder_seq_length: ${.seq_length}

aux:  # auxiliary configuration arguments that are free and not typed
  model_name: ""
