data_path:
 - ${oc.env:OELLM_DATASETS_TOKENIZED_DIR}/gpt-neox-20b/nemotron-cc/1.0/high-actual
 - ${oc.env:OELLM_DATASETS_TOKENIZED_DIR}/gpt-neox-20b/nemotron-cc/1.0/high-synthetic-distill
 - ${oc.env:OELLM_DATASETS_TOKENIZED_DIR}/gpt-neox-20b/nemotron-cc/1.0/high-synthetic-diverse_qa_pairs
 - ${oc.env:OELLM_DATASETS_TOKENIZED_DIR}/gpt-neox-20b/nemotron-cc/1.0/high-synthetic-extract_knowledge
 - ${oc.env:OELLM_DATASETS_TOKENIZED_DIR}/gpt-neox-20b/nemotron-cc/1.0/high-synthetic-knowledge_list
 - ${oc.env:OELLM_DATASETS_TOKENIZED_DIR}/gpt-neox-20b/nemotron-cc/1.0/high-synthetic-wrap_medium
