axes:
  megatron.lr: [0.0003, 0.0002]
  megatron.micro_batch_size: [4, 8]
base_values:
  run_name: megatron_sweep
name_template: "${project.name}_{run_name}_m{megatron.micro_batch_size}_lr{megatron.lr}_{index}"
store_sweep_json: true
