name: demo
log_path: ${.base_output_dir}/${oc.if:${slurm.array},slurm-%A_%a.log,slurm-%j.log}
log_path_current: ${.base_output_dir}/current${oc.if:${slurm.array}, "_${index}", ""}.log
config_path: ${.base_output_dir}/${oc.if:${slurm.array},slurm-%A_%a.log,config-%j.yaml}
config_path_current: ${.base_output_dir}/current${oc.if:${slurm.array}, "_${index}", ""}.yaml
base_output_dir: ${oc.concat:${oc.env:OUTPUT_DIR,"./output"}/,${job.name}${oc.if:${slurm.array}, "_${index}", ""}}

slurm: ${slurm}  # ! do not change this

start_condition: null
cancel_condition: null
