defaults:
  - _self_

template_path: templates/base.sbatch
script_dir: ${project.base_output_dir}
log_dir: ${project.base_output_dir}
array: true
submit_cmd: sbatch
launcher_cmd: "python"
launcher_env_passthrough: false
env: {}
srun: {}
sbatch:
  nodes: 1
  ntasks_per_node: 1
  cpus_per_task: 8
  time: "01:00:00"
  account: ${oc.env:SLURM_ACCOUNT,"dev"}
  partition: ${oc.env:SLURM_PARTITION,"default"}
  gres: "gpu:1"
  gpus_per_node: 4
  # output is set to null so orchestrator uses job.log_path
  # job.log_path comes from monitoring.log_path_template (formatted with job details)
  output: null
test_only: false
client:
  class_name: FakeSlurmClient
