defaults:
  - _self_

template_path: templates/base.sbatch
script_dir: ./generated/sbatch
log_dir: ./logs
array: true
submit_cmd: sbatch
launcher_cmd: ""
srun_opts: ""
sbatch_overrides:
  nodes: 1
  ntasks_per_node: 1
  cpus_per_task: 8
  time: "01:00:00"
  partition: debug
  account: default
  gres: "gpu:1"
sbatch_extra_directives: []
test_only: false
