class_name: Container
image: ${oc.env:CONTAINER_CACHE_DIR,.}/MegatronTraining_base2512_aarch64_202602031731.sif
runtime: apptainer
bind: []
env:
  WANDB_MODE: "offline"
  MACHINE_NAME: "JUPITER"
  PYTHONPATH: "."
python: "python"
