class_name: Container
image: /leonardo_work/OELLM_prod2026/container_images/nemo_25.11.01.sif
runtime: singularity
bind: ["/leonardo_scratch", "/leonardo", "/leonardo_work/OELLM_prod2026/"]
env:
  WANDB_MODE: "offline"
  MACHINE_NAME: "LEONARDO"
  PYTHONPATH: "."
python: "/usr/bin/python"
