image: ${oc.env:CONTAINER_CACHE_DIR,.}/MegatronTraining_x86_64_202512291044.sif
runtime: singularity
bind: ["/leonardo_scratch"]
env:
  WANDB_MODE: "offline"
  PYTHONPATH: "."
python: "/usr/bin/python"
