class_name: Container
image: ${oc.env:OELLM_CONTAINERS_DIR,.}/OELLM_autoexp_MegatronTrainingNoRoot_base2512_x86_64_202601281510.sif
runtime: singularity
bind: ["/leonardo_scratch", "/leonardo", "/leonardo_work"]
env:
  WANDB_MODE: "offline"
  MACHINE_NAME: "LEONARDO"
  PYTHONPATH: "."
python: "/usr/bin/python"
