class_name: Container
image: ${oc.env:CONTAINER_CACHE_DIR,.}/MegatronTrainingNoRoot_base2512_x86_64_202601281510.sif
runtime: singularity
bind: ["/gpfs/projects"]
env:
  WANDB_MODE: "offline"
  PYTHONPATH: "."
  MACHINE_NAME: "MARENOSTRUM"
python: "python"
