image: ${oc.env:CONTAINER_CACHE_DIR,.}/MegatronTraining_x86_64_202512291044.sif
runtime: singularity
bind: ["/gpfs/projects"]
env:
  WANDB_MODE: "offline"
  PYTHONPATH: "."
  MACHINE_NAME: "MARENOSTRUM"
python: "python"
