defaults:
  - megatron: base
  - _self_

class_name: AutoMegatronBackend
launcher_script: "python ${.env.RUN_DIR}/pretrain_gpt.py"
use_torchrun: false
python_cmd: "python"
full_validation: true
env:
  PYTHONPATH: ".:submodules/Megatron-LM"
  PROJECT_DIR: ${oc.env:PROJECT_DIR,"."}
  RUN_DIR: ${.PROJECT_DIR}/submodules/Megatron-LM
